### ISSUE TITLE
Chapter 1-2 discussion -- The Algorithm Design Manual

### ISSUE THREAD

**Issue by sax** [sax/book_club#1]
April 4?

**Comment by sax** [comment]
Thinking Apr 4 for a retrospective on the chapters. I'm also free the 28th for working through exercises.

**Comment by sax** [comment]
@hjhart @richardiux @kigster @wizjo

**Comment by eanakashima** [comment]
@mattyoho

**Comment by sax** [comment]
- @toriscallan
- @rachelmyers

**Comment by rachelmyers** [comment]
Yay!

:closed_book: :ok_woman: :computer:

**Comment by sax** [comment]
- @jn80842

**Comment by hjhart** [comment]
Books are neat!

**Comment by sax** [comment]
I'm thinking the 28th around 12:30pm to work through some exercises. Does that work for everyone?

**Comment by jn80842** [comment]
I'm in for the 28th.

**Comment by sax** [comment]
Just wanted to remind people that some of us are getting together at 12:30 today to work through exercises. We're doing a hackday at Wanelo, so there won't be any time pressures. I was thinking an hour or so.

I've found Chapter 2 to be much more understandable than Chapter 1, and next week will likely go back and re-read the first chapter to review it. Next week I'm going to look around for some online math review resources, just to get back some of the polynomial functions and transformations.

**Comment by rachelmyers** [comment]
I'm planning on joining in today! :book: :hamburger:

**Comment by richardiux** [comment]
http://nbl.cewit.stonybrook.edu:60128/mediawiki/index.php/TADM2E_2.8

**Comment by mattyoho** [comment]
Sorry, I missed today due to an :eyes: doctor's appointment, but I'll make the next session and schedule doctor visits strategically going forward.

**Comment by sax** [comment]
We wound up talking through big oh notation and how to determine whether a function f(n) was O(g(n)), Ω(g(n)) or θ(g(n)). I think all of us were banging around in the closets of our brains for the math, so hopefully I'll be able to find some math refreshers this weekend and post them.

Hope to see you next week!
