### ISSUE TITLE
Chapter 3 — The Algorithm Design Manual

### ISSUE THREAD

**Issue by sax** [sax/book_club#2]
Hey all! I've been busy this week dealing things related to the Heartbleed OpenSSL vulnerability. I have it on good authority that this bug was caused by an Algorithm™.

Last week we decided that our next bit of reading was going to be Chapter 3 of the Algorithm Design Manual. That makes this Friday, April 11, our day of working through exercises in Chapter 3.

@hjhart has volunteered to write down some notes on the chapter, to give an overview for those who have not had a chance to read.

/cc @hjhart @richardiux @kigster @wizjo @mattyoho @toriscallan @rachelmyers @jn80842 @eanakashima @letuboy

**Comment by sax** [comment]
Just a reminder that we're meeting again tomorrow to do a retrospective on Chapter 3. Hope to see people there!

**Comment by jn80842** [comment]
Hey all, looks like I can't make it tomorrow (I need to prep for an afternoon meeting). Let me know what the reading is for next week!
