### ISSUE TITLE
Chapter 5 — The Algorithm Design Manual

### ISSUE THREAD

**Issue by sax** [sax/book_club#4]
Yay Chapter 5!

Just a reminder that we're not meeting this week, and will continue with Chapter 5 next week.

**Comment by eanakashima** [comment]
Did we officially move book group to Thursday at 12:00 @ GitHub this week? Can't remember.

**Comment by eanakashima** [comment]
We also could bump it to next week if y'all are busy patching things.

**Comment by sax** [comment]
Ooh. Just woke up. No matter what, I'm going to be late!

Sent from my iPhone

On Jun 5, 2014, at 9:51 AM, Emily Nakashima notifications@github.com
wrote:

We also could bump it to next week if y'all are busy patching things.

**Comment by eanakashima** [comment]
Since @rachelmyers is out of town and the Wanelo crew was up late, let's pick back up next Friday.
